# Generated by Django 3.0.6 on 2020-05-31 10:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200530_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('ds', 'Data Structure'), ('algo', 'Algorithm'), ('tech', 'Tech Update'), ('life', 'Life Learning')], default='ds', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
